"""
PDF Export using fpdf2.
Generates a professional, downloadable travel itinerary PDF.
"""
from fpdf import FPDF
from models.schemas import ItineraryPlan
import io


class TravelPDF(FPDF):
    def header(self):
        self.set_fill_color(30, 58, 138)  # Deep blue
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 18, "  ✈  AI Travel Agent — Trip Execution Package", ln=True)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by AI Travel Agent  •  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(239, 246, 255)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 58, 138)
        self.cell(0, 9, f"  {title}", ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(1)

    def body_text(self, text: str, indent: int = 4):
        self.set_font("Helvetica", "", 9)
        self.set_x(self.get_x() + indent)
        self.multi_cell(0, 5, text)

    def kv_row(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 6, f"  {key}:", border=0)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, str(value))


def generate_pdf(itinerary: ItineraryPlan) -> bytes:
    """Generate a PDF and return bytes."""
    pdf = TravelPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    prefs = itinerary.preferences
    opt = itinerary.selected_option

    # ── Cover / Trip Summary ────────────────────────────────────────────────
    pdf.section_title("📍 Trip Summary")
    pdf.kv_row("Destination", prefs.destination)
    pdf.kv_row("Origin", prefs.origin)
    pdf.kv_row("Duration", f"{prefs.duration_days} days")
    pdf.kv_row("Travel Dates", prefs.travel_dates or "As planned")
    pdf.kv_row("Total Budget", f"₹{prefs.total_budget_inr:,.0f}")
    pdf.kv_row("Style", opt.style)
    pdf.kv_row("Plan Option", f"Option {opt.label}")
    pdf.kv_row("Interests", ", ".join(prefs.interests))

    # ── Transport ───────────────────────────────────────────────────────────
    pdf.section_title("🚆 Transport Booking")
    t = itinerary.transport_booking
    pdf.kv_row("Mode", t.name)
    pdf.kv_row("Route", t.location or f"{prefs.origin} → {prefs.destination}")
    pdf.kv_row("Cost (per person)", f"₹{t.cost_inr:,.0f}")
    pdf.kv_row("Duration", t.duration or "—")
    pdf.kv_row("Book at", t.booking_url)
    if t.notes:
        pdf.kv_row("Tips", t.notes)

    # ── Hotel ───────────────────────────────────────────────────────────────
    pdf.section_title("🏨 Stay Booking")
    h = itinerary.hotel_booking
    nights = prefs.duration_days - 1
    pdf.kv_row("Property", h.name)
    pdf.kv_row("Location", h.location or prefs.destination)
    pdf.kv_row("Cost", f"₹{h.cost_inr:,.0f}/night × {nights} = ₹{h.cost_inr * nights:,.0f}")
    if h.rating:
        pdf.kv_row("Rating", f"{h.rating} / 5.0")
    pdf.kv_row("Book at", h.booking_url)
    if h.notes:
        pdf.kv_row("Features", h.notes)

    # ── Budget Breakdown ────────────────────────────────────────────────────
    pdf.section_title("💰 Budget Breakdown")
    budget = itinerary.budget_breakdown
    for cat in budget.categories:
        pdf.kv_row(cat.category, f"₹{cat.amount_inr:,.0f}  —  {cat.description}")
    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 7, f"  Projected Total: ₹{budget.projected_total_inr:,.0f}   |   Buffer Remaining: ₹{budget.remaining_buffer_inr:,.0f}", ln=True)
    pdf.set_text_color(0, 0, 0)

    # ── Day-by-Day Itinerary ────────────────────────────────────────────────
    for day in itinerary.days:
        pdf.section_title(f"🗓 {day.title}")
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 5, f"  Day cost: ₹{day.total_cost_inr:,.0f}", ln=True)
        pdf.ln(1)
        for block in day.blocks:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(250, 250, 250)
            pdf.cell(0, 6, f"  ⏰ {block.time}  —  {block.activity}", ln=True, fill=True)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_x(pdf.get_x() + 6)
            pdf.multi_cell(0, 5, block.description)
            if block.cost_inr > 0:
                pdf.cell(0, 4, f"     💰 Cost: ₹{block.cost_inr:,.0f}", ln=True)
            else:
                pdf.cell(0, 4, "     💰 Free", ln=True)
            if block.booking_url:
                pdf.set_font("Helvetica", "U", 8)
                pdf.set_text_color(30, 58, 138)
                pdf.cell(0, 4, f"     🔗 {block.booking_url}", ln=True)
                pdf.set_text_color(0, 0, 0)
            if block.tips:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(80, 80, 80)
                pdf.cell(0, 4, f"     💡 {block.tips}", ln=True)
                pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

    # ── Activities ──────────────────────────────────────────────────────────
    if itinerary.activity_bookings:
        pdf.section_title("🎯 Key Activities & Booking Links")
        for act in itinerary.activity_bookings:
            pdf.kv_row(act.name, f"₹{act.cost_inr:,.0f}  |  {act.booking_url}")

    # ── Final Budget Summary ────────────────────────────────────────────────
    pdf.section_title("📊 Final Budget Summary")
    pdf.kv_row("Estimated Total", f"₹{itinerary.total_estimated_cost_inr:,.0f}")
    pdf.kv_row("Total Budget", f"₹{prefs.total_budget_inr:,.0f}")
    pdf.kv_row("Remaining", f"₹{itinerary.remaining_budget_inr:,.0f}")

    # ── Booking Checklist ───────────────────────────────────────────────────
    if itinerary.booking_checklist:
        pdf.section_title("📌 Booking Checklist")
        for item in itinerary.booking_checklist:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, f"  ☐  {item}", ln=True)

    # ── Insider Tips ────────────────────────────────────────────────────────
    if itinerary.insider_tips:
        pdf.section_title("💡 Insider Tips")
        for tip in itinerary.insider_tips:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, f"  •  {tip}", ln=True)

    return bytes(pdf.output())
