"""
PDF Export using fpdf2.
Generates a professional, downloadable travel itinerary PDF.
"""
from fpdf import FPDF
from models.schemas import ItineraryPlan
import re


# ── Unicode cleaner (Helvetica only supports Latin-1) ────────────────────────
def clean(text: str) -> str:
    """Strip emojis and replace non-Latin-1 chars with ASCII equivalents."""
    text = str(text)
    # Common replacements
    text = text.replace("₹", "Rs.")
    text = text.replace("→", "->")
    text = text.replace("—", "-")
    text = text.replace("–", "-")
    text = text.replace("•", "*")
    text = text.replace("☐", "[ ]")
    text = text.replace("…", "...")
    # Drop anything remaining outside Latin-1 (emojis, Devanagari, etc.)
    text = text.encode("latin-1", "ignore").decode("latin-1")
    return text


class TravelPDF(FPDF):
    def header(self):
        self.set_fill_color(30, 58, 138)  # Deep blue
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 18, "  AI Travel Agent -- Trip Execution Package", ln=True)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by AI Travel Agent  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(239, 246, 255)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 58, 138)
        self.cell(0, 9, f"  {clean(title)}", ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(1)

    def body_text(self, text: str, indent: int = 4):
        self.set_font("Helvetica", "", 9)
        self.set_x(self.get_x() + indent)
        self.multi_cell(0, 5, clean(text))

    def kv_row(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 6, f"  {clean(key)}:", border=0)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, clean(str(value)))


def generate_pdf(itinerary: ItineraryPlan) -> bytes:
    """Generate a PDF and return bytes."""
    pdf = TravelPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    prefs = itinerary.preferences
    opt = itinerary.selected_option

    # ── Cover / Trip Summary ────────────────────────────────────────────────
    pdf.section_title("Trip Summary")
    pdf.kv_row("Destination", prefs.destination)
    pdf.kv_row("Origin", prefs.origin)
    pdf.kv_row("Duration", f"{prefs.duration_days} days")
    pdf.kv_row("Travel Dates", prefs.travel_dates or "As planned")
    pdf.kv_row("Total Budget", f"Rs.{prefs.total_budget_inr:,.0f}")
    if opt:
        pdf.kv_row("Style", opt.style)
        pdf.kv_row("Plan Option", f"Option {opt.label}")
    pdf.kv_row("Interests", ", ".join(prefs.interests))

    # ── Transport ───────────────────────────────────────────────────────────
    if itinerary.transport_booking:
        pdf.section_title("Transport Booking")
        t = itinerary.transport_booking
        pdf.kv_row("Mode", t.name)
        pdf.kv_row("Route", t.location or f"{prefs.origin} -> {prefs.destination}")
        pdf.kv_row("Cost (per person)", f"Rs.{t.cost_inr:,.0f}")
        pdf.kv_row("Duration", t.duration or "-")
        pdf.kv_row("Book at", t.booking_url or "-")
        if t.notes:
            pdf.kv_row("Tips", t.notes)

    # ── Hotel ───────────────────────────────────────────────────────────────
    if itinerary.hotel_booking:
        pdf.section_title("Stay Booking")
        h = itinerary.hotel_booking
        nights = prefs.duration_days - 1
        pdf.kv_row("Property", h.name)
        pdf.kv_row("Location", h.location or prefs.destination)
        pdf.kv_row("Cost", f"Rs.{h.cost_inr:,.0f}/night x {nights} = Rs.{h.cost_inr * nights:,.0f}")
        if h.rating:
            pdf.kv_row("Rating", f"{h.rating} / 5.0")
        pdf.kv_row("Book at", h.booking_url or "-")
        if h.notes:
            pdf.kv_row("Features", h.notes)

    # ── Budget Breakdown ────────────────────────────────────────────────────
    if itinerary.budget_breakdown:
        pdf.section_title("Budget Breakdown")
        budget = itinerary.budget_breakdown
        for cat in budget.categories:
            pdf.kv_row(cat.category, f"Rs.{cat.amount_inr:,.0f}  -  {cat.description}")
        pdf.ln(1)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(
            0, 7,
            clean(f"  Projected Total: Rs.{budget.projected_total_inr:,.0f}   |   Buffer: Rs.{budget.remaining_buffer_inr:,.0f}"),
            ln=True,
        )
        pdf.set_text_color(0, 0, 0)
        if budget.optimization_notes:
            pdf.ln(1)
            pdf.set_font("Helvetica", "I", 8.5)
            pdf.set_x(pdf.get_x() + 4)
            pdf.multi_cell(0, 5, clean(f"Notes: {budget.optimization_notes}"))

    # ── Day-by-Day Itinerary ────────────────────────────────────────────────
    for day in itinerary.days:
        pdf.section_title(f"Day {day.day_number} - {clean(day.title.split('–')[-1].strip()) if '–' in day.title else clean(day.title)}")
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 5, f"  Estimated cost: Rs.{day.total_cost_inr:,.0f}", ln=True)
        pdf.ln(1)

        for block in day.blocks:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(248, 250, 255)
            pdf.cell(0, 6, f"  {clean(block.time)}  -  {clean(block.activity)}", ln=True, fill=True)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_x(pdf.get_x() + 6)
            pdf.multi_cell(0, 5, clean(block.description or ""))
            cost_str = f"Rs.{block.cost_inr:,.0f}" if block.cost_inr > 0 else "Free"
            pdf.cell(0, 4, f"     Cost: {cost_str}", ln=True)
            if block.booking_url:
                pdf.set_font("Helvetica", "U", 8)
                pdf.set_text_color(30, 58, 138)
                pdf.cell(0, 4, f"     Book: {block.booking_url}", ln=True)
                pdf.set_text_color(0, 0, 0)
            if block.tips:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(80, 80, 80)
                pdf.cell(0, 4, clean(f"     Tip: {block.tips}"), ln=True)
                pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

    # ── Activities ──────────────────────────────────────────────────────────
    if itinerary.activity_bookings:
        pdf.section_title("Key Activities & Booking Links")
        for act in itinerary.activity_bookings:
            pdf.kv_row(act.name, f"Rs.{act.cost_inr:,.0f}  |  {act.booking_url or '-'}")

    # ── Final Budget Summary ────────────────────────────────────────────────
    pdf.section_title("Final Budget Summary")
    pdf.kv_row("Estimated Total", f"Rs.{itinerary.total_estimated_cost_inr:,.0f}")
    pdf.kv_row("Total Budget", f"Rs.{prefs.total_budget_inr:,.0f}")
    pdf.kv_row("Remaining", f"Rs.{itinerary.remaining_budget_inr:,.0f}")

    # ── Booking Checklist ───────────────────────────────────────────────────
    if itinerary.booking_checklist:
        pdf.section_title("Booking Checklist")
        for item in itinerary.booking_checklist:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, clean(f"  [ ]  {item}"), ln=True)

    # ── Insider Tips ────────────────────────────────────────────────────────
    if itinerary.insider_tips:
        pdf.section_title("Insider Tips")
        for tip in itinerary.insider_tips:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, clean(f"  *  {tip}"), ln=True)

    return bytes(pdf.output())
